//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metamorph {
    
    
    public partial class _Default {
        
        /// <summary>
        /// ctlDepartmentDecreases control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.department_changes ctlDepartmentDecreases;
        
        /// <summary>
        /// lblCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCount;
        
        /// <summary>
        /// lblTotal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotal;
        
        /// <summary>
        /// ctlDepartmentIncreases control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.department_changes ctlDepartmentIncreases;
        
        /// <summary>
        /// ctlDepartments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater ctlDepartments;
        
        /// <summary>
        /// ctlTopSpenders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_spenders ctlTopSpenders;
        
        /// <summary>
        /// ctlTopSpendersForYear2010 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_spenders ctlTopSpendersForYear2010;
        
        /// <summary>
        /// ctlTopSpendersForYear2009 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_spenders ctlTopSpendersForYear2009;
        
        /// <summary>
        /// ctlTopSpendersForYear2008 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_spenders ctlTopSpendersForYear2008;
        
        /// <summary>
        /// ctlTopSpendersForYear2007 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_spenders ctlTopSpendersForYear2007;
        
        /// <summary>
        /// ctlTopSpendersForYear2006 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_spenders ctlTopSpendersForYear2006;
        
        /// <summary>
        /// ctlTopSpendersForYear2005 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_spenders ctlTopSpendersForYear2005;
        
        /// <summary>
        /// ctlTopSpendersForYear2004 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_spenders ctlTopSpendersForYear2004;
    }
}
