//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metamorph {
    
    
    public partial class largest_expenses {
        
        /// <summary>
        /// ctlLargestExpenses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_expenses ctlLargestExpenses;
        
        /// <summary>
        /// ctlMostExpensiveFlights control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_flights ctlMostExpensiveFlights;
        
        /// <summary>
        /// ctlLargestExpenses2009 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_expenses ctlLargestExpenses2009;
        
        /// <summary>
        /// ctlLargestExpenses2008 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_expenses ctlLargestExpenses2008;
        
        /// <summary>
        /// ctlLargestExpenses2007 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_expenses ctlLargestExpenses2007;
        
        /// <summary>
        /// ctlLargestExpenses2006 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_expenses ctlLargestExpenses2006;
        
        /// <summary>
        /// ctlLargestExpenses2005 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_expenses ctlLargestExpenses2005;
        
        /// <summary>
        /// ctlLargestExpenses2004 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.top_expenses ctlLargestExpenses2004;
    }
}
