//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metamorph {
    
    
    public partial class smallest_expenses {
        
        /// <summary>
        /// ctlSmallestExpenses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.lowest_expenses ctlSmallestExpenses;
        
        /// <summary>
        /// ctlSmallestExpenses2009 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.lowest_expenses ctlSmallestExpenses2009;
        
        /// <summary>
        /// ctlSmallestExpenses2008 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.lowest_expenses ctlSmallestExpenses2008;
        
        /// <summary>
        /// ctlSmallestExpenses2007 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.lowest_expenses ctlSmallestExpenses2007;
        
        /// <summary>
        /// ctlSmallestExpenses2006 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.lowest_expenses ctlSmallestExpenses2006;
        
        /// <summary>
        /// ctlSmallestExpenses2005 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.lowest_expenses ctlSmallestExpenses2005;
        
        /// <summary>
        /// ctlSmallestExpenses2004 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.lowest_expenses ctlSmallestExpenses2004;
    }
}
