//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metamorph {
    
    
    public partial class trip_duration {
        
        /// <summary>
        /// ctlLongestTrips control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.trip_duration1 ctlLongestTrips;
        
        /// <summary>
        /// ctlLongestTrips2009 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.trip_duration1 ctlLongestTrips2009;
        
        /// <summary>
        /// ctlLongestTrips2008 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.trip_duration1 ctlLongestTrips2008;
        
        /// <summary>
        /// ctlLongestTrips2007 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.trip_duration1 ctlLongestTrips2007;
        
        /// <summary>
        /// ctlLongestTrips2006 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.trip_duration1 ctlLongestTrips2006;
        
        /// <summary>
        /// ctlLongestTrips2005 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.trip_duration1 ctlLongestTrips2005;
        
        /// <summary>
        /// ctlLongestTrips2004 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.trip_duration1 ctlLongestTrips2004;
        
        /// <summary>
        /// ctlLongestAverageTrips control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.trip_duration1 ctlLongestAverageTrips;
    }
}
