//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metamorph {
    
    
    public partial class expense_count {
        
        /// <summary>
        /// lblCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCount;
        
        /// <summary>
        /// ctlRangeReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater ctlRangeReport;
        
        /// <summary>
        /// ctlMostExpenses2009 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlMostExpenses2009;
        
        /// <summary>
        /// ctlMostExpenses2008 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlMostExpenses2008;
        
        /// <summary>
        /// ctlMostExpenses2007 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlMostExpenses2007;
        
        /// <summary>
        /// ctlMostExpenses2006 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlMostExpenses2006;
        
        /// <summary>
        /// ctlMostExpenses2005 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlMostExpenses2005;
        
        /// <summary>
        /// ctlMostExpenses2004 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlMostExpenses2004;
        
        /// <summary>
        /// ctlLeastExpenses2009 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlLeastExpenses2009;
        
        /// <summary>
        /// ctlLeastExpenses2008 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlLeastExpenses2008;
        
        /// <summary>
        /// ctlLeastExpenses2007 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlLeastExpenses2007;
        
        /// <summary>
        /// ctlLeastExpenses2006 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlLeastExpenses2006;
        
        /// <summary>
        /// ctlLeastExpenses2005 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlLeastExpenses2005;
        
        /// <summary>
        /// ctlLeastExpenses2004 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Metamorph.most_expenses ctlLeastExpenses2004;
    }
}
